# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Akash'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr create --resource-group Python --name dumbo123 --location southcentralus --sku Standard'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Akash'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks create --resource-group Python --name aksclusters --node-count 1 --enable-addons monitoring --generate-ssh-keys --attach-acr dumbo123 --location brazilsouth'
- task: Docker@2
  inputs:
    containerRegistry: 'dumbo'
    repository: 'pythonapplication'
    command: 'buildAndPush'
    Dockerfile: 'Python/Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Akash'
    azureResourceGroup: 'Python'
    kubernetesCluster: 'akscluster'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'Python/deployment.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'