# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubantu-latest

steps:
 #task: AzureCLI@2
  #inputs:
   # azureSubscription: 'Akash'
    #scriptType: 'ps'
    #scriptLocation: 'inlineScript'
    #inlineScript: 'az acr create --resource-group Python --name dumbo --location eastus --sku Standard'
# task: AzureCLI@2
 # inputs:
  #  azureSubscription: 'Akash'
   # scriptType: 'ps'
    #scriptLocation: 'inlineScript'
    #inlineScript: 'az aks create --resource-group Python --name akscluster --node-count 3 --enable-addons monitoring --generate-ssh-keys --attach-acr dumbo --location westeurope'
- task: Docker@2
  inputs:
    containerRegistry: 'dumbo'
    repository: 'pythonapplication'
    command: 'build'
    Dockerfile: 'Python/Dockerfile'
    tags: 'latest'
- task: Docker@2
  inputs:
    containerRegistry: 'dumbo'
    repository: 'pythonapplication'
    command: 'push'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Akash'
    azureResourceGroup: 'Python'
    kubernetesCluster: 'akscluster'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'Python/deployment.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'