apiVersion : apps/v1
kind: Deployment
metadata:
  name: pythonapplication 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapplication
  template:
    metadata:
      labels:
        app: pythonapplication 
    spec:
      containers:
        - name: pythonapplication 
          image: dumbo.azurecr.io/pythonapplication
          ports:
          - containerPort: 8501