apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-streamlit-app
  template:
    metadata:
      labels:
        app: my-streamlit-app
    spec:
      containers:
      - name: my-streamlit-app
        image: dumbo.azurecr.io/pythonapplication:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: my-streamlit-service
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501
  selector:
    app: my-streamlit-app
